INSERT INTO Director (id, first_name, last_name, birth_date) VALUES (1, 'James', 'Cameron', '1954-08-16');
INSERT INTO Director (id, first_name, last_name, birth_date) VALUES (2, 'Quentin', 'Tarantino', '1963-03-27');
INSERT INTO Director (id, first_name, last_name, birth_date) VALUES (3, 'David', 'Fincher', '1962-08-28');
INSERT INTO Director (id, first_name, last_name, birth_date) VALUES (4, 'Tommy', 'Wiseau', '1955-10-03');
INSERT INTO Director (id, first_name, last_name, birth_date) VALUES (5, 'Michelle', 'Obama', '1964-01-17');

INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (1, 1, 'Piranha II: The Spawning', '1982-08-14', 'Thriller');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (2, 1, 'The Terminator', '1984-10-26', 'Sci-fi');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (3, 1, 'Aliens', '1986-07-18', 'Thriller');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (4, 1, 'The Abyss', '1989-08-09', 'Sci-fi');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (5, 1, 'Terminator 2: Judgment Day', '1991-07-01', 'Sci-fi');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (6, 1, 'True Lies', '1994-07-15', 'Action');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (7, 1, 'Titanic', '1997-11-18', 'Drama');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (8, 1, 'Avatar', '2009-12-10', 'Fantasy');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (9, 2, 'Reservoir Dogs', '1992-09-02', 'Crime');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (10, 2, 'Pulp Fiction', '1994-09-10', 'Crime');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (11, 2, 'Jackie Brown', '1997-12-25', 'Crime');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (12, 2, 'Kill Bill: Volume 1', '2003-10-10', 'Thriller');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (13, 2, 'Kill Bill: Volume 2', '2003-10-10', 'Thriller');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (14, 2, 'Inglourious Basterds', '2009-07-28', 'Dark comedy');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (15, 2, 'Django Unchained', '2012-12-25', 'Western');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (16, 2, 'The Hateful Eight', '2016-01-14', 'Western');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (17, 2, 'Once Upon a Time in Hollywood', '2019-07-24', 'Comedy-Drama');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (18, 3, 'Alien 3', '1992-05-22', 'Action-Horror');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (19, 3, 'Se7en', '1995-12-10', 'Crime Thriller');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (20, 3, 'The Game', '1997-09-12', 'Thriller');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (21, 3, 'Fight Club', '1999-09-10', 'Drama');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (22, 3, 'Panic Room', '2002-03-18', 'Thriller');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (23, 3, 'Zodiac', '2007-03-02', 'Crime Thriller');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (24, 3, 'The Curious Case of Benjamin Button', '2008-12-10', 'Drama');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (25, 3, 'The Social Network', '2010-10-01', 'Drama');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (26, 3, 'The Girl with the Dragon Tattoo', '2011-12-12', 'Crime Thriller');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (27, 3, 'Gone Girl', '2014-10-16', 'Drama');
INSERT INTO Film (id, director_id, name, release_date, genre) VALUES (28, 4, 'The Room', '2003-05-27', 'Drama');